# Spécifier le nom de l'utilisateur qui va exécuter nginx afin de limiter les risques de sécurité
# user www-data;

# Spécifier le nombre de processus nginx qui vont être lancés
worker_processes auto;

# Spécifier le chemin des fichiers de log d'erreur
error_log /var/log/nginx/error.log;

# Spécifier le chemin contenant le PID (Process ID) de nginx
pid /run/nginx.pid;

events {
    # Nombre maximum de connexions simultanées
    worker_connections 1024;
    # Accepter plusieurs connexions au même moment
    # multi_accept on;
}

http {
    ##
    # Paramètres de base
    ##
    # Temps d'attente maximum pour recevoir les données envoyées par le client
    # Envoyer les fichiers statiques (images, css, js) directement au client plutôt que de les passer par nginx
    sendfile on;
    # Format des logs
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    # Emplacement des logs d'accès
    access_log  /var/log/nginx/access.log  main;

    ##
    # Paramètres des hôtes virtuels (sous-domaines)
    ##
    include conf.d/*.conf;
    
    ##
    # Paramètres des fichiers
    ##
    # Définir les types de fichiers connus par nginx
    include /etc/nginx/mime.types;
    # Définir le type de fichier par défaut
    default_type application/octet-stream;
    # Nombre maximum de types de fichiers gérables par nginx
    types_hash_max_size 2048;

    ##
    # Paramètres réseau
    ##
    # Envoyer les headers HTTP en une seule fois
    tcp_nopush on;
    # Désactiver le buffering des données envoyées au client (envoi immédiat sans attendre que le buffer soit rempli)
    tcp_nodelay on;
    # Temps d'attente maximum pour recevoir les données envoyées par le client
    keepalive_timeout 65;

    ##
    # Paramètres de gzip (compression des fichiers envoyés au client)
    ##
    gzip on;
	# Désactiver la compression des fichiers pour les clients qui ne supportent pas la compression
    gzip_disable "msie6";

}
