    
    server 
    {  
        # URL du site
        server_name localhost;
        # Écoute sur le port 80
        listen 80 default_server;  
        # Accès aux fichiers statiques dans le conteneur
        root /var/www/html/public;  
        # Index par défaut en .php, sinon .html
        index index.php index.html;  

        # Encodage de caractères à utiliser pour les fichiers statiques
        charset utf-8;  
        
        # Pour permettre la lecture des fichiers par PHP, 
        # il faut désactiver sendfile qui envoie les fichiers statiques directement au client
        sendfile off; 
        # Taille maximale des fichiers envoyés par le client
        client_max_body_size 100m; 

        # Désactiver le log des accès
        access_log off;  
        # Chemin des logs d'erreur
        error_log /var/log/nginx/error.log error;  
    
        # Configuration nécessaire au fonctionnement de PHP-FPM
        location ~ .php$ { 
            # Afficher l'erreur 404 si le fichier n'existe pas
            try_files $uri =404;
            # Découper le chemin d'accès pour récupérer le nom du fichier
            fastcgi_split_path_info ^(.+.php)(/.+)$;  
            # À configurer selon le service Docker (cf. docker-compose.yml: nom:port)
            fastcgi_pass php:9000; 
            fastcgi_index index.php;
            # Inclure les paramètres par défaut de PHP-FPM  
            include fastcgi_params;  
            # Customiser les paramètres de PHP-FPM
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_intercept_errors off;  
            fastcgi_buffer_size 16k;  
            fastcgi_buffers 4 16k;  
        }

        # Désactiver les logs d'erreur pour les requêtes vers ces fichier
        location = /favicon.ico {
            access_log off;
            log_not_found off;
        }  
        location = /robots.txt {
            access_log off;
            log_not_found off;
        }  

        # Interdire les requêtes vers les fichiers .htaccess, .htpasswd ou autre s'ils existent
        location ~ /.ht {  
            deny all;  
        }
    }